language: generic

sudo: required
services: 
  -  docker

before_intall:
  - docker build -t pheanoukpel-docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true pheanoukpel-docker-react npm run test -- --coverage