language: generic

sudo: required
services: 
  -  docker

before_intall:
  - docker build -t apel73/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true apel73/docker-react npm run test -- --coverage